version: '3.1'

services:
  postgres:
    image: postgres
    container_name: mydatabase-postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mydatabase-network

  redis:
    image: redis
    container_name: mydatabase-redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:

networks:
  mydatabase-network:
